### ISSUE TITLE
Catkin : command not found 

### ISSUE THREAD

**Issue by kjyothiswaroop** [ntnu-arl/gbplanner_ws#6]
Hello everyone!,

I had followed the instructions given on the repository and while performing the last two lines to build the repository the following error pops us : 

![Screenshot from 2021-09-13 17-12-19](https://user-images.githubusercontent.com/51844889/133077539-f7d9cdbd-cafd-4356-96c6-17e2835a737e.png)

Please provide a resolution for this. Thanks!

**Comment by yyjplus** [comment]
You need to install it. Use this command:
sudo apt-get install python-catkin-tools

**Comment by yyjplus** [comment]
> Hello everyone!,
> 
> I had followed the instructions given on the repository and while performing the last two lines to build the repository the following error pops us :
> 
> ![Screenshot from 2021-09-13 17-12-19](https://user-images.githubusercontent.com/51844889/133077539-f7d9cdbd-cafd-4356-96c6-17e2835a737e.png)
> 
> Please provide a resolution for this. Thanks!

You need to install it. Use this command:
sudo apt-get install python-catkin-tools
